ConsumerKey=3MVG99PRsqIQWIIzMgq5BVydpkPbQAW6ljLDQlTlxjX6a7NC3tOKXl_gs6J7.fO4cBSpz3vmeJGv2D_4N6xuM
ConsumerSecret=B284B74C48A77CD46F959324FCA83E77A3D5D04C757BA2607D94FBE27D4C14C1
user.name=test-81yrhvbcskya@example.com


    private String loginUrl="https://test.salesforce.com";
    private String keyStorePath="/Users/bobby.white/.keystore";
    private String keyStorePassword="CaseModel";
    private String certAlias="server";
    private String pkPassword="CaseModel";